//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB_Studio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>#Set1</string>
  <string>#Set2</string>
  <string>#Set3</string>
  <string>#Set4</string>
  <string>#Set5</string>
  <string>#Set6</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection setNames {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["setNames"]));
            }
            set {
                this["setNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0|0|0|0|0|0</string>
  <string>0|0|0|0|0|0</string>
  <string>0|0|0|0|0|0</string>
  <string>0|0|0|0|0|0</string>
  <string>0|0|0|0|0|0</string>
  <string>0|0|0|0|0|0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection setAttribs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["setAttribs"]));
            }
            set {
                this["setAttribs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>-</string>
  <string>-</string>
  <string>-</string>
  <string>-</string>
  <string>-</string>
  <string>-</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection setItems {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["setItems"]));
            }
            set {
                this["setItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>-</string>
  <string>-</string>
  <string>-</string>
  <string>-</string>
  <string>-</string>
  <string>-</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection setItemsFlags {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["setItemsFlags"]));
            }
            set {
                this["setItemsFlags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Projects\\")]
        public string projectsFolderPath {
            get {
                return ((string)(this["projectsFolderPath"]));
            }
            set {
                this["projectsFolderPath"] = value;
            }
        }
    }
}
